# Generated by Django 2.2.26 on 2022-03-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_app_plan_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='subscription',
        ),
    ]
